### PR TITLE
LICENSE: add title; collapse double newline at EOF

### PR DESCRIPTION
**Pull request by waldyrious**
The title is not legally mandated, but it's recommended in the license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license).

*This PR is part of a project to improve the consistency and visibility of the ISC license. See https://github.com/github/choosealicense.com/issues/377 for more details.*

### CODE REVIEW

**Comment by waldyrious** [comment]
Hi @juliohm. Would you mind indicating the reasoning for the closure? Thanks.

**Comment by juliohm** [comment]
Hi @waldyrious , as with other PRs that you submitted, I am not interested in changing the format of the LICENSE, I am sorry.

If you are really interested in changing the format of the ISC license, you should contact OSI and try to change the license header there: https://opensource.org/licenses

**Comment by waldyrious** [comment]
Understood. I think it may be subjective whether the title is part of the license text or not, at https://opensource.org/licenses/isc-license; as an additional data point, SPDX seems to consider it part of the text, per https://spdx.org/licenses/ISC.html. In any case, thanks for the explanation.

ps - for future reference, some of the similar PRs I have sent are https://github.com/juliohm/GeoStats.jl/pull/16 and https://github.com/juliohm/ImageQuilting.jl/pull/9. (I'll make sure to cross-reference any remaining ones if I dig up the links.)

**Comment by waldyrious** [comment]
Ok, I think I found all the remaining PRs, and closed the ones that were still open. For previous discussion, see https://github.com/juliohm/GeoStatsImages.jl/pull/2.

**Pull request closed without merging**
